### ISSUE TITLE
View current scale of each server dyno (Size and Count)

### ISSUE THREAD

**Issue by johnknaack** [Cjones90/HerokuGitStatus#1]

**Comment by codeopensrc** [comment]
Added with latest commit: 676407be6db2841ebfdb2a321fe41bf507296345

**Comment by codeopensrc** [comment]
Also wanted to note, I was able to remove the .json file dependency. The only side effect is if the current heroku repo is pushed directly from a local repo/branch without it being pushed to Github, it won't show.
